[package]
name = "pollard-git"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
gix = { version = "0.87.1", default-features = false, features = ["sha1", "revision"] }
pollard-objects = { version = "0.1.0", path = "../pollard-objects" }
thiserror = "2.0.20"

[dev-dependencies]
tempfile = "3.27.0"
